"""adjust users table

Revision ID: 5e1be9970fab
Revises: 5dafe24f425d
Create Date: 2026-05-21 18:36:16.739477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e1be9970fab"
down_revision: Union[str, Sequence[str], None] = "5dafe24f425d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("sub", sa.String(), nullable=False))
    op.add_column("users", sa.Column("picture", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["sub"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "picture")
    op.drop_column("users", "sub")
    # ### end Alembic commands ###
